icons_format = "{icon}"

[theme]
theme = "semi-native"

[icons]
icons = "awesome6"

[[block]]
block = "cpu"
format_alt = " $icon $barchart "

#[[block]]
#block = "temperature"

#[[block]]
#block = "load"
#format = " $icon $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon $mem_total_used_percents.eng(w:2) ($mem_avail.eng(w:1,prefix:M) free of $mem_total.eng(w:1,prefix:M)) "

[[block]]
block = "nvidia_gpu"
format = " $icon $utilization $memory.eng(w:1) "
interval = 5

#[[block]]
#block = "docker"

#[[block]]
#block = "pacman"

#[[block]]
#block = "net"

[[block]]
block = "disk_space"
alert_unit = "GB"
warning = 50.0
alert = 20.0

# too distracting
#[[block]]
#block = "music"
#format = " $icon {$combo.str(max_w:25)} "

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %b %d %I:%M %p') "
#format = " $timestamp.datetime(f:'%a %b %d %l:%M %p') "
